version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-inventory
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_go_clean
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: inventory-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: